### ISSUE TITLE
more structure covariance structures?

### ISSUE THREAD

**Issue by skyee1** [covaruber/sommer#32]
I wonder if more covariance structures can be used. For example, AR, ARMA, FA(q), FA0(q)

**Comment by covaruber** [comment]
We have some functionalities for AR,ARMA but they require the correlation parameter to be provided and is not estimated. For spatial models the two dimensional spline functions are available. See the vignettes for some examples.

With respect to FA modeling we're working to have first the mme-based version of the average information since the direct-inversion that is currently implemented is not suitable for FA analysis. Once we have the mme-based AI algorithm coded in C++ we will start working on the FA implementation.
