### ISSUE TITLE
mmer fails when number of observations > 2^15 

### ISSUE THREAD

**Issue by nikitautiu** [covaruber/sommer#43]
### How to reproduce

Here's a minimal example with synthetic data. We are fitting one fixed and one random effect for 32800 observations. **NOTE:** Given the high number of rows, this takes quite a bit to run. The 32000 case is used just to prove the point that values below 2^15 are not affected and may be commented out.

```r
library(conflicted)
library(tidyverse)
library(sommer)


# generate 32800 synthetic observations
data <- tibble(
  fixA = runif(32800, 0, 5),
  ranB = as.factor(sample.int(2, 32800, replace = TRUE))
) %>%
  mutate(val = -2 + 
           fixA * 0.7 + 
           as.numeric(ranB == 1) * rnorm(32800, mean = 1, sd = 0.2) +
           as.numeric(ranB == 0) * rnorm(32800, mean = 1, sd = 0.7) +
           rnorm(32800, 0, 0.01)
  )

print(paste("TEST WITH 1000:", Sys.time()))
# should run just fine with a few observations
model <- mmer(
  fixed = val ~ fixA,
  random = ~ ranB,
  rcov = ~ units,
  data = data %>%  slice_sample(n = 1000), 
  verbose = TRUE
)

print(paste("TEST WITH 32000:", Sys.time()))
# should run just fine with 32000
model <- mmer(
  fixed = val ~ fixA,
  random = ~ ranB,
  rcov = ~ units,
  data = data %>%  slice_sample(n = 32000), 
  verbose = TRUE
)

print(paste("TEST WITH 32800:", Sys.time()))
# crashes with segfault for 32800
model <- mmer(
  fixed = val ~ fixA,
  random = ~ ranB,
  rcov = ~ units,
  data = data, 
  verbose = TRUE
)
```

### Expected behaviour
The code should run all the instances of `mmer`

###  Actual behaviour
`mmer` fails when fitting 32800 observations with a **segmentation fault**. Noticed this happened around 32000 so I tested different values. I guess this could be a signed 2 byte variable going out of range? 

### Notes

I found this out when trying to implement a somewhat automated pipeline which had convergence issues with `mmec` and didn't want to spend time on tweaking the step weight. 

If this is intended or is outside the scope of `mmer` maybe it can be documented as it is quite difficult to debug?

**Comment by covaruber** [comment]
Dear @nikitautiu, indeed the mmer function is not suited for n > p problems which is why I have invested considerable time developing the mmec function so you can deal with greater number of records. I would try first checking that the argument tolParConvNorm  has a small value < 0.005 so is only using the likelihood tolParConvLL. If that still provides convergence issues then indeed you would need to finetune the emWeight argument so it gives more weight to the EM information matrix in the first iterations.

The mmer function really needs to be refurbished to use S4 objects and avoid memory issues when passing the objects to C++. This is in my to do list but it may take a couple of months before I get there. But even fixing the memory issues it needs to be clear that the direct inversion algorithm is not suited for big n.

Cheers,
Eduardo

**Comment by nikitautiu** [comment]
Hi Eduardo,

Thanks for the feedback. Indeed in my case I might benefit from setting `tolParConvNorm` to a small value as the since the log likelihood does not plateau. However in some edge cases I think I still need to tweak the step weight as the log-likelihood is unstable and doesn't show any signs of convergence.

Thanks for the suggestions overall!

**Comment by covaruber** [comment]
I think what you have to tune is the emWeight argument instead of the stepWeight. That should help convergence more. The current approach assumes that after few iterations (~8) all variance components are close to their maximum and the emWeight is 0.04. Maybe you can set something less aggressive like emWeight=c(seq(1,.2,-.05), rep(.2,100)) so in any iteration you stay within the boundaries and avoid singularities. I am following the approach from Madsen and Jensen but very likely asreml has other heuristics principles that I still have to figure out. As you can see the mmec() function is making its first appearance :) thanks for reporting this though, lots of things to improve.

Cheers,
Eduardo

**Comment by covaruber** [comment]
The mmec() function has been running well for now and is the only solution that will be enabled for this issue. I am closing the issue now. Thanks!

Eduardo
